sonar.projectKey=shadday123_hangout-service
sonar.organization=shadday123
sonar.host.url=https://sonarcloud.io
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.exclusions=**/model/**,**/dto/**,**/enums/**,**/config/*,**/mapper/*,**/exception/*,**/*Application*,**/persistence/entity/**,**/util/*,**/exceptions/**,**/events/**,**/messaging/**,**/repository/**
