# Local development overrides — activate with --spring.profiles.active=local
spring.rabbitmq.password=eHWjGdLhNYN73Ct96wUAV1KkpwnDiKZj
spring.datasource.url=jdbc:postgresql://localhost:5433/hangoutdb
