name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: hangoutdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
          - 5672:5672
        options: >-
          --health-cmd "rabbitmq-diagnostics ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Compilar y ejecutar tests
        run: mvn clean verify
        env:
          PGHOST: localhost
          PGPORT: 5432
          PGDATABASE: hangoutdb
          PGUSER: postgres
          PGPASSWORD: postgres
          RABBITMQ_HOST: localhost
          RABBITMQ_PORT: 5672
          RABBITMQ_USERNAME: guest
          RABBITMQ_PASSWORD: guest
          RABBITMQ_VHOST: /
          RABBITMQ_SSL: false
          JWT_SECRET: ${{ secrets.JWT_SECRET_TEST }}

      - name: Subir JAR como artifact
        uses: actions/upload-artifact@v4
        with:
          name: hangout-service-jar
          path: target/*.jar
          retention-days: 14

      - name: Subir reporte JaCoCo
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/
          retention-days: 14

      - name: Subir resultados Surefire
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports/
          retention-days: 14
